---
title: "Anàlisi per escoles"
author: "Unitat de Bioestadística"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
require(psych)
require(plyr)
require(nFactors)
require(ggplot2)
require(GGally)
require(reshape2)
require(plotly)
require(mice)
source('ggbiplot.R')
```

```{r}
noms = c("Reading", "Errors Reading", "Working_memory","Errors Working memory", "Visual_processing_speed", "Errors Visual processing speed", "Mathematical_fluency", "Errors Mathematical fluency", "Long_term_memory", "Errors Long term memory","Reasoning", "Errors_Reasoning", "Escola")

pre1 = read.csv('resultats_barem/tots - primer.csv', header = FALSE, encoding = "UTF-8")

pre1 = pre1[,c(2:13,1)]

colnames(pre1)=noms
pre2 = read.csv('resultats_barem/tots - segon.csv', header = FALSE, encoding = "UTF-8")
pre2 = pre2[,c(2:13,1)]
colnames(pre2)=noms

pre3 = read.csv('resultats_barem/tots - tercer.csv', header = FALSE, encoding = "UTF-8")
noms_prov = names(pre3)
pre3 = pre3[,c(2:17,1)]
names(pre3) = noms_prov[1:17]
pre3$V3 =as.numeric(as.character(pre3$V3)) +as.numeric(as.character(pre3$V5))
pre3$V4 = as.numeric(as.character(pre3$V4))+as.numeric(as.character(pre3$V6))
pre3$V11 =as.numeric(as.character(pre3$V11)) +as.numeric(as.character(pre3$V13))
pre3$V12 = as.numeric(as.character(pre3$V12))+as.numeric(as.character(pre3$V14))
pre3 = pre3[,-c(5:6,13:14)]
colnames(pre3)=noms

pre4 = read.csv('resultats_barem/tots - quart.csv', header = FALSE, encoding = "UTF-8")
noms_prov = names(pre4)
pre4 = pre4[,c(2:17,1)]
names(pre4) = noms_prov[1:17]
pre4$V3 =as.numeric(as.character(pre4$V3)) +as.numeric(as.character(pre4$V5))
pre4$V4 = as.numeric(as.character(pre4$V4))+as.numeric(as.character(pre4$V6))
pre4$V11 =as.numeric(as.character(pre4$V11)) +as.numeric(as.character(pre4$V13))
pre4$V12 = as.numeric(as.character(pre4$V12))+as.numeric(as.character(pre4$V14))
pre4 = pre4[,-c(5:6,13:14)]
colnames(pre4)=noms

pre5 = read.csv('resultats_barem/tots - cinquè.csv', header = FALSE, encoding = "UTF-8")
noms_prov = names(pre5)
pre5 = pre5[,c(2:23,1)]
names(pre5) = noms_prov[1:23]
pre5$V3 =as.numeric(as.character(pre5$V3)) + 
  as.numeric(as.character(pre5$V3)) + as.numeric(as.character(pre5$V7))
pre5$V4 = as.numeric(as.character(pre5$V4))+
  as.numeric(as.character(pre5$V6))+as.numeric(as.character(pre5$V8))

pre5$V13 =as.numeric(as.character(pre5$V13)) +
  as.numeric(as.character(pre5$V15)) + as.numeric(as.character(pre5$V17))
pre5$V14 = as.numeric(as.character(pre5$V14)) + 
  as.numeric(as.character(pre5$V16)) + as.numeric(as.character(pre5$V18))

pre5 = pre5[,-c(5:8,15:18)]
precalc5 = pre5[,c(13,14)] # per utilitzar després
pre5 = pre5[,-c(13,14)] # també trec càlcul
colnames(pre5)=noms


pre6 = read.csv('resultats_barem/tots - sisè.csv', header = FALSE, encoding = "UTF-8")
noms_prov = names(pre6)
pre6 = pre6[,c(2:23,1)]
names(pre6) = noms_prov[1:23]
pre6$V3 =as.numeric(as.character(pre6$V3)) + 
  as.numeric(as.character(pre6$V3)) + as.numeric(as.character(pre6$V7))
pre6$V4 = as.numeric(as.character(pre6$V4))+
  as.numeric(as.character(pre6$V6))+as.numeric(as.character(pre6$V8))
pre6$V13 =as.numeric(as.character(pre6$V13)) +
  as.numeric(as.character(pre6$V15)) + as.numeric(as.character(pre6$V17))
pre6$V14 = as.numeric(as.character(pre6$V14)) + 
  as.numeric(as.character(pre6$V16)) + as.numeric(as.character(pre6$V18))

pre6 = pre6[,-c(5:8,15:18)]
precalc6 = pre6[,c(13,14)] # per utilitzar després
pre6 = pre6[,-c(13,14)] # també trec càlcul
colnames(pre6)=noms

```

```{r}
pre1$curs = rep(1, nrow(pre1))
pre2$curs = rep(2, nrow(pre2))
pre3$curs = rep(3, nrow(pre3))
pre4$curs = rep(4, nrow(pre4))
pre5$curs = rep(5, nrow(pre5))
precalc5$curs = rep(5, nrow(precalc5))
pre6$curs = rep(6, nrow(pre6))
precalc6$curs = rep(6, nrow(precalc6))

for (j in 1:12){
  pre1[,j] = as.numeric(as.character(pre1[,j]))
  pre2[,j] = as.numeric(as.character(pre2[,j]))
  pre3[,j] = as.numeric(as.character(pre3[,j]))
  pre4[,j] = as.numeric(as.character(pre4[,j]))
  pre5[,j] = as.numeric(as.character(pre5[,j]))
  pre6[,j] = as.numeric(as.character(pre6[,j]))
}

for (j in 1:2){
  precalc5[,j] = as.numeric(as.character(precalc5[,j]))
  precalc6[,j] = as.numeric(as.character(precalc6[,j]))
}
```

```{r}
coefs = c(0.25,0.5,0.2,0.2,0.5,0.33)

for (j in 1:6){
  pre1[,j*2-1] = pre1[,j*2-1]-coefs[j]*pre1[,j*2]
  pre2[,j*2-1] = pre2[,j*2-1]-coefs[j]*pre2[,j*2]
  pre3[,j*2-1] = pre3[,j*2-1]-coefs[j]*pre3[,j*2]
  pre4[,j*2-1] = pre4[,j*2-1]-coefs[j]*pre4[,j*2]
  pre5[,j*2-1] = pre5[,j*2-1]-coefs[j]*pre5[,j*2]
  pre6[,j*2-1] = pre6[,j*2-1]-coefs[j]*pre6[,j*2]
}

pre1 = pre1[,-c(2,4,6,8,10,12)]
pre2 = pre2[,-c(2,4,6,8,10,12)]
pre3 = pre3[,-c(2,4,6,8,10,12)]
pre4 = pre4[,-c(2,4,6,8,10,12)]
pre5 = pre5[,-c(2,4,6,8,10,12)]
pre6 = pre6[,-c(2,4,6,8,10,12)]

precalc5[,1] = precalc5[,1]-0.25*precalc5[,2]
precalc6[,1] = precalc6[,1]-0.25*precalc6[,2]

precalc5[,2] = NULL
precalc6[,2] = NULL
```

```{r}
for (j in 1:6){
  pre1[,j] = (pre1[,j]-mean(pre1[,j], na.rm=TRUE))/sd(pre1[,j], na.rm=TRUE)
  pre2[,j] = (pre2[,j]-mean(pre2[,j], na.rm=TRUE))/sd(pre2[,j], na.rm=TRUE)
  pre3[,j] = (pre3[,j]-mean(pre3[,j], na.rm=TRUE))/sd(pre3[,j], na.rm=TRUE)
  pre4[,j] = (pre4[,j]-mean(pre4[,j], na.rm=TRUE))/sd(pre4[,j], na.rm=TRUE)
  pre5[,j] = (pre5[,j]-mean(pre5[,j], na.rm=TRUE))/sd(pre5[,j], na.rm=TRUE)
  pre6[,j] = (pre6[,j]-mean(pre6[,j], na.rm=TRUE))/sd(pre6[,j], na.rm=TRUE)
}
tots = rbind(pre1,pre2,pre3,pre4,pre5,pre6)

tt = tots
# Netegem un outlier de Working memory
tt$`Working_memory`[tt$`Working_memory`>5]<-NA

```

No feu cas d'aquests warnings, ara no els puc treure...:

```{r, message=F, warning=F}
aa = mice(tt, method = 'cart')
tc = complete(aa)
```

```{r, message=F, warning=F}
precalc5[,1] = (precalc5[,1]-mean(precalc5[,1], na.rm=TRUE))/sd(precalc5[,1], na.rm=TRUE)
precalc6[,1] = (precalc6[,1]-mean(precalc6[,1], na.rm=TRUE))/sd(precalc6[,1], na.rm=TRUE)
totscalc = rbind(precalc5,precalc6)
bb = mice(totscalc, method = 'cart')
tcca = complete(bb)

```


## Anàlisi gràfic

```{r}
ggplot(tc, aes(Escola, Reading, colour = Escola)) + 
  geom_boxplot() + 
  theme_bw()
```

```{r}
ggplot(tc, aes(Escola, Working_memory, colour = Escola)) + 
  geom_boxplot() + 
  theme_bw()
```

```{r}
ggplot(tc, aes(Escola, Visual_processing_speed, colour = Escola)) + 
  geom_boxplot() + 
  theme_bw()
```

```{r}
ggplot(tc, aes(Escola, Mathematical_fluency, colour = Escola)) + 
  geom_boxplot() + 
  theme_bw()
```

```{r}
ggplot(tc, aes(Escola, Long_term_memory, colour = Escola)) + 
  geom_boxplot() + 
  theme_bw()
```

```{r}
ggplot(tc, aes(Escola, Reasoning, colour = Escola)) + 
  geom_boxplot() + 
  theme_bw()
```

PCA
===


```{r}
prout = prcomp(tc[,1:6])
#km.out = kmeans(data.matrix(tc[,1:6]), centers=5, nstart = 100)
```

```{r Fig2, fig.width=10, fig.height=10}
g <- ggbiplot(prout, obs.scale = 1, var.scale = 1, choices = c(1,2),
              groups = tc$Escola,ellipse = TRUE, 
              circle = TRUE, aplha = 1, varname.size = 4) +
  scale_color_discrete(name = '') + 
  theme(legend.direction = 'vertical', 
               legend.position = 'right') + 
  labs(title = 'Biplot showing first and second principal components', 
       subtitle = "Colors indicate schools") +
  theme_light()

print(g)
#ggsave("biplot_12",g,"png")
```

```{r Fig3, fig.width=10, fig.height=10}
g <- ggbiplot(prout, obs.scale = 1, var.scale = 1, choices = c(1,3),
              groups = tc$Escola,ellipse = TRUE, 
              circle = TRUE, aplha = 0.5, varname.size = 4) +
  scale_color_discrete(name = '') + 
  theme(legend.direction = 'vertical', 
               legend.position = 'right') + 
  labs(title = 'Biplot showing first and third principal components', 
       subtitle = "Colors indicate schools") + 
  theme_light()

print(g)
#ggsave("biplot_13",g,"png")

```

```{r}
p <- plot_ly(as.data.frame(prout$x), x = ~PC1, y = ~PC2, z = ~PC3, color = ~tc$Escola, size = .7) %>%
  add_markers() %>%
  layout(scene = list(xaxis = list(title = 'PC1'),
                     yaxis = list(title = 'PC2'),
                     zaxis = list(title = 'PC3')))
p
```

```{r}
write.csv(tc, "dades_tots_escalades.csv", row.names = F)
```

